config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'static_pages#home'

  resources :assessments
  resources :users, :only => [:index, :destroy]
  resources :test_logs, :only => [:index, :destroy]

  get '/available_tests', to: 'assessments#available_tests'
  get '/get_questions', to: 'assessments#get_questions'
  get '/score_test', to: 'assessments#score_test'
end

app/models/assessment.rb
require 'net/http'
require 'openssl'
require 'uri'

# == Schema Information
#
# Table name: assessments
#
#  id            :bigint           not null, primary key
#  topic         :string           not null
#  num_questions :integer          default(5), not null
#  advanced      :boolean          default(FALSE), not null
#  content       :text
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#
class Assessment < ApplicationRecord
  validates :topic, :presence => true, :uniqueness => true
  validates_inclusion_of :advanced, :in => [true, false]
  validates_numericality_of :num_questions, :integer_only => true, :greater_than_or_equal_to => 3

  def has_content?
    if self.content.blank?
      false
    else
      self.content.include?('"question"')
    end
  end

  def question_display
    if self.content.blank?
      ""
    else
      obj = JSON.parse(self.content)
      result = ''
      obj.each do |q|
        result += "#{q['question']}&nbsp;&nbsp;("
        q['choices'].each do |c|
          result += "#{c['choice']}, "
        end
        result = result[0..result.length-3]
        result += ")<br>"
      end

      result
    end
  end

  def notify_test_added
    base_url = ENV['METACERT_EXPRESS_ENDPOINT']

    url = URI.parse("#{base_url}/addtest")
    http = Net::HTTP.new(url.host, url.port)
    http.use_ssl = true
    http.verify_mode = OpenSSL::SSL::VERIFY_NONE
    
    # Prepare the request
    request = Net::HTTP::Post.new(url)
    request["Content-Type"] = 'application/json'
    request.body = "{\"id\": \"#{self.id}\"}"
    
    response = http.request(request)
    puts response.read_body
  end
end

app/controllers/assessments_controller.rb
require 'openai_chat'

class AssessmentsController < ApplicationController
  include ApplicationHelper

  respond_to :html

  PASSING_SCORE = 80

  def index
    @tests = Assessment.order(:topic)
  end
  
  def new
    @test = Assessment.new
  end
  
  def create
    @test = Assessment.new(test_params)

    begin
      if @test.save
        redirect_to assessments_path, :notice => 'Test successfully created'
      else
        render 'new'
      end  
    rescue Exception => ex
      @test.errors.add :base, ex.message
      
      render 'new'
    end   
  end
  
  def edit
    @test = Assessment.find(params[:id])
  end
  
  def update
    @test = Assessment.find(params[:id])
    
    begin
      @test.assign_attributes(test_params)
      @test.content = OpenAIChat.instance.generate_prompt(@test.topic, @test.num_questions, @test.advanced)

      if @test.save
        begin
          @test.notify_test_added
        rescue Exception => ex
          puts ex.inspect
        end

        redirect_to assessments_path, :notice => 'Test successfully updated'
      else
        render 'edit'
      end
    rescue Exception => ex
      @test.errors.add :base, ex.message
      
      render 'edit'
    end   
  end
  
  def destroy
    @test = Assessment.find(params[:id])
    @test.destroy
    
    redirect_to assessments_path, :notice => 'Test successfully deleted'    
  end
  
  # Get a list of the tests that are available
  def available_tests
    # id, name
    data = []
    Assessment.order(:topic).each do |a|
      data.push({:id => a.id, :name => a.topic})
    end

    render json: data, content_type: 'application/json'
  end

  # Get the questions for a particular test
  def get_questions
    test_id = params[:id]

    test = Assessment.find_by_id(test_id)
    result = {"ERROR": "Test not found"}

    # Filter out the answers, since this is an open get
    unless test.nil?
      obj = JSON.parse(test.content)
      result = []
      obj.each do |q|
        o = {}
        q.keys.each do |k|
          next if k == 'answer'
          o[k] = q[k]
        end 
        result.push(o)
      end
    end

    render :json => result, content_type: 'application/json'
  end

  # Results are in the form of test id, address of user, [{questionId, choice}]
  def score_test
    puts params

    a = Assessment.find_by_id(params[:id])
    if a.nil?
      status = "ERROR: Test not found"
    else
      user_id = params[:address]

      if user_id.length != 42
        status = "ERROR: Invalid user address"
      else
        user = User.find_by_address(user_id)
        if user.nil?
          user = User.create(:address => user_id)
        end

        n = a.num_questions.to_f
        correct = 0.0

        answer_key = JSON.parse(a.content)
        key = Hash.new
        answer_key.each do |k|
          qid = k["questionId"].to_i
          key[qid] = k["answer"].to_i
        end
        
        # Record the users answers in a hash :answer_id => choice (as numbers)
        answers = Hash.new
        idx = 1
        params[:choices].split(',').each do |choice|
          answers[idx] = choice.to_i
          idx += 1
        end

        if answers.length == n
          answers.keys.each do |k|
            if answers[k] == key[k]
              correct += 1.0
            end
          end

          score = (correct / n * 100.0).round
          passed = score >= PASSING_SCORE
          status = "Success"
          if passed
            begin
              user.mint_poap(a.id)
            rescue Exception => ex
              puts ex.inspect
            end
          end

          user.test_logs.create(:assessment_id => a.id, :score => score, :passed => passed)
        else
          status = "ERROR: Question mismatch; cannot score"
        end
      end
    end

    render :json => {:status => status, :passed => passed}
  end

private
  def test_params
    params.require(:assessment).permit(:topic, :content, :num_questions, :advanced)
  end
end

app/views/assessments/_test_fields.html.haml
.field
  = f.label :topic, 'Test topic'
  = f.text_field :topic
.field
  = f.label :num_questions, 'How many questions'
  = f.number_field :num_questions, :min => 3, :max => 10
.field
  = f.check_box :advanced
  = f.label :advanced, :style => 'display:inline'

app/views/assessments/edit.html.haml
- provide(:title, 'Edit/Update Test')
.c_customer.afclr
  .wrapper
    .re_main.afclr
      .ab_head.afclr
        %h1== Generate test on '#{@test.topic}'
      .in_iner_pag.afclr
        %h3 Current Questions and Answers
        - if @test.content.blank?
          No content yet
        - else
          = @test.question_display.html_safe
        %br
        = form_for @test do |f|
          = render :partial => 'shared/generic_error_messages', :locals => { :errors => @test.errors, :name => 'Test' }
          = render :partial => 'test_fields', :locals => { :f => f }
          .actions
            = f.submit 'Update Test', :class => 'btn btn-primary'
          %br
          = link_to 'Done', assessments_path

app/views/assessments/index.html.haml
- provide(:title, 'Assessments')
.c_customer.afclr
  .wrapper
    .re_main.afclr
      .ab_head.afclr
        %h1 Available Tests
        %br= link_to 'Add Test', new_assessment_path, :class => 'btn btn-primary'
      .in_iner_pag.afclr
        %table.table.table-striped
          %thead
            %tr
              %th ID
              %th Topic
              %th Level
              %th Questions
              %th Generated?
              %th
          %tbody
            - @tests.each do |t|
              %tr
                %td= t.id
                %td= link_to t.topic, edit_assessment_path(t)
                %td= t.advanced ? 'Advanced' : 'Simple'
                %td= t.num_questions
                %td= t.has_content? ? 'Yes' : 'No'
                %td= button_to 'Delete', t, :method => :delete        
        .center

app/views/assessments/new.html.haml
- provide(:title, 'New Client')
.c_customer.afclr
  .wrapper
    .re_main.afclr
      .ab_head.afclr
        %h1 New Client
      .in_iner_pag.afclr
        = form_for @test do |f|
          = render :partial => 'shared/generic_error_messages', :locals => { :errors => @test.errors, :name => 'Test' }
          = render :partial => 'test_fields', :locals => { :f => f }
          .actions
            = f.submit 'Create Test', :class => 'btn btn-primary'
            %br
            = link_to 'Back', assessments_path